# Generated by Django 3.1.3 on 2020-11-19 10:36

from django.db import migrations, models
import django_countries.fields
import parametres.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('consultation', models.PositiveIntegerField(default=0, verbose_name='NOMBRE DE CONSULTATION')),
                ('prix', models.PositiveIntegerField(default=2500)),
                ('details', models.TextField()),
            ],
            options={
                'verbose_name': 'abonnement',
                'verbose_name_plural': 'ABONNEMENTS',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('reponses', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'faq',
                'verbose_name_plural': 'FAQS',
            },
        ),
        migrations.CreateModel(
            name='Hopital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='CODE')),
                ('libelle', models.CharField(max_length=250, verbose_name='NOM')),
                ('pays', django_countries.fields.CountryField(max_length=2)),
                ('ville', models.CharField(max_length=250, verbose_name='VILLE')),
                ('adresse', models.CharField(blank=True, max_length=250, verbose_name='ADRESSE')),
                ('telephone1', phonenumber_field.modelfields.PhoneNumberField(help_text='+22545485648', max_length=128, region=None)),
                ('telephone2', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='+22545485648', max_length=128, region=None)),
                ('faxe', models.CharField(blank=True, max_length=50, verbose_name='FAXE')),
                ('email', models.EmailField(blank=True, max_length=120, verbose_name='ADRESSE EMAIL')),
                ('siteweb', models.CharField(blank=True, max_length=120, verbose_name='SITE WEB')),
                ('logo', models.ImageField(blank=True, upload_to=parametres.models.upload_logo_site, verbose_name='Logo')),
                ('image1', models.ImageField(blank=True, upload_to=parametres.models.upload_logo_site, verbose_name='Image 1')),
                ('image2', models.ImageField(blank=True, upload_to=parametres.models.upload_logo_site, verbose_name='Image 2')),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'hopital',
                'verbose_name_plural': 'HOPITAUX',
            },
        ),
        migrations.CreateModel(
            name='Pathologie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'pathologie',
                'verbose_name_plural': 'PATHOLOGIES',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('details', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='%Y%m')),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'SERVICES',
            },
        ),
        migrations.CreateModel(
            name='Symptome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptome', models.CharField(max_length=500, verbose_name='SYMPTOME')),
            ],
            options={
                'verbose_name': 'symptome',
                'verbose_name_plural': 'SYMPTOMES',
                'ordering': ['symptome'],
            },
        ),
    ]
