# Generated by Django 3.2.6 on 2021-11-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adulte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptome', models.CharField(max_length=500, verbose_name='SYMPTOME')),
            ],
            options={
                'verbose_name': 'symptome adulte',
                'verbose_name_plural': 'SYMPTOMES ADULTES',
                'ordering': ['symptome'],
            },
        ),
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptome', models.CharField(max_length=500, verbose_name='SYMPTOME')),
            ],
            options={
                'verbose_name': 'symptome nourrisson et enfant',
                'verbose_name_plural': 'SYMPTOMES NOURRISSONS ET ENAFANTS',
                'ordering': ['symptome'],
            },
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, verbose_name='CODE PAYS')),
                ('libelle', models.CharField(max_length=255, verbose_name='NOM PAYS')),
            ],
            options={
                'verbose_name': 'pays',
                'verbose_name_plural': 'PAYS',
            },
        ),
        migrations.DeleteModel(
            name='Pathologie',
        ),
        migrations.DeleteModel(
            name='Symptome',
        ),
        migrations.AddField(
            model_name='abonnement',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hopital',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
