# Generated by Django 3.2.6 on 2021-11-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdv',
            name='date_rdv',
            field=models.DateField(blank=True, null=True, verbose_name='DATE DU RDV'),
        ),
        migrations.AlterField(
            model_name='rdv',
            name='heure_rdv',
            field=models.TimeField(blank=True, null=True, verbose_name='HEURE DU RDV'),
        ),
        migrations.AlterUniqueTogether(
            name='rdv',
            unique_together=set(),
        ),
    ]
