# Generated by Django 3.2.6 on 2021-11-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_rdv_date_rdv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdv',
            name='date_rdv',
            field=models.DateField(verbose_name='DATE DU RDV'),
        ),
    ]
